### ISSUE TITLE
Assembly Skywire miner hardware

### ISSUE THREAD

**Issue by litvintech** [cybLabs/skywire-mesh#1]

**Comment by mrlp4** [comment]
- [ ] Buy some screws fro final assembly with ABS corner holders; board legs.

- [ ] Cut some 2020 profile to make cubical frame

- [ ] Develop design of boards holder

- [ ] Find power cord for switch

**Comment by mrlp4** [comment]
- [ ] Buy power connectors for boards 

- [ ] buy power wires, power distribution bus
